config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :site_configs

  resources :page_meta_infos

  resources :home_sliders

  resources :work_sliders

  resources :team_sliders

  resources :service_sliders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  #resources :services
  get '/service', :to => "services#index", :as => :services
  get	'/service/:short_link(.:format)', :to=>'services#show', :as=>:service


  #resources :teams
  get '/team', :to => "teams#index", :as => :teams
  get	'/team/:short_link(.:format)', :to=>'teams#show', :as=>:team

  #resources :works,:only=>[:index, :show], except: :destroy
  get '/work', :to => "works#index", :as => :works
  get	'/work/:short_link(.:format)', :to=>'works#show', :as=>:work

  #resources :contacts
  get '/contact', :to => "contacts#new", :as => :new_contact
  post '/contact', :to => "contacts#create", :as => :create_contact
  resources :contacts, :only => [:new, :create], :path => 'contacts'

  #resources :project_planners
  get '/project-planner', :to => "project_planners#new", :as => :new_project_planner
  post '/project-planner', :to => "project_planners#create", :as => :create_project_planner
  resources :project_planners, :only => [:new, :create], :path => 'project_planners'

  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/home_slider.rb
class HomeSlider < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
end

app/models/page_meta_info.rb
class PageMetaInfo < ActiveRecord::Base
end

app/models/page_setting.rb
class PageSetting < ActiveRecord::Base
end

app/models/project_planner.rb
class ProjectPlanner < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :homepage_icon, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :homepage_icon_hover, :styles => { :medium => "300x300>", :thumb=> "100x100>" }

  validates_attachment :homepage_icon, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  validates_attachment :homepage_icon_hover, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  has_many :service_sliders

  def to_param
    short_link
  end
end

app/models/service_slider.rb
class ServiceSlider < ActiveRecord::Base
  has_attached_file :navigation_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :navigation_image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :service
end

app/models/site_config.rb
class SiteConfig < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  has_many :team_sliders

  def to_param
    short_link
  end

end

app/models/team_slider.rb
class TeamSlider < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  has_many :work_sliders

  def to_param
    short_link
  end
end

app/models/work_slider.rb
class WorkSlider < ActiveRecord::Base
  has_attached_file :navigation_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :navigation_image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :work
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @services = Service.all
    @home_sliders = HomeSlider.order('home_sliders.order').all
  end
end

app/controllers/service_sliders_controller.rb
class ServiceSlidersController < InheritedResources::Base

  private

    def service_slider_params
      params.require(:service_slider).permit(:service_short_description, :order, :active_class, :active_html, :navigation_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/service_sliders_helper.rb
module ServiceSlidersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/service_sliders/_form.html.erb
<%= form_for(@service_slider) do |f| %>
  <% if @service_slider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_slider.errors.count, "error") %> prohibited this service_slider from being saved:</h2>

      <ul>
      <% @service_slider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service_short_description %><br>
    <%= f.text_field :service_short_description %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :active_class %><br>
    <%= f.text_field :active_class %>
  </div>
  <div class="field">
    <%= f.label :active_html %><br>
    <%= f.text_field :active_html %>
  </div>
  <div class="field">
    <%= f.label :navigation_image %><br>
    <%= f.text_field :navigation_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_sliders/edit.html.erb
<h1>Editing service_slider</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_slider %> |
<%= link_to 'Back', service_sliders_path %>

app/views/service_sliders/index.html.erb
<h1>Listing service_sliders</h1>

<table>
  <thead>
    <tr>
      <th>Service short description</th>
      <th>Order</th>
      <th>Active class</th>
      <th>Active html</th>
      <th>Navigation image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_sliders.each do |service_slider| %>
      <tr>
        <td><%= service_slider.service_short_description %></td>
        <td><%= service_slider.order %></td>
        <td><%= service_slider.active_class %></td>
        <td><%= service_slider.active_html %></td>
        <td><%= service_slider.navigation_image %></td>
        <td><%= link_to 'Show', service_slider %></td>
        <td><%= link_to 'Edit', edit_service_slider_path(service_slider) %></td>
        <td><%= link_to 'Destroy', service_slider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service slider', new_service_slider_path %>

app/views/service_sliders/new.html.erb
<h1>New service_slider</h1>

<%= render 'form' %>

<%= link_to 'Back', service_sliders_path %>

app/views/service_sliders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service short description:</strong>
  <%= @service_slider.service_short_description %>
</p>

<p>
  <strong>Order:</strong>
  <%= @service_slider.order %>
</p>

<p>
  <strong>Active class:</strong>
  <%= @service_slider.active_class %>
</p>

<p>
  <strong>Active html:</strong>
  <%= @service_slider.active_html %>
</p>

<p>
  <strong>Navigation image:</strong>
  <%= @service_slider.navigation_image %>
</p>

<%= link_to 'Edit', edit_service_slider_path(@service_slider) %> |
<%= link_to 'Back', service_sliders_path %>