config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :site_configs

  resources :page_meta_infos

  resources :home_sliders

  resources :work_sliders

  resources :team_sliders

  resources :service_sliders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  #resources :services
  get '/service', :to => "services#index", :as => :services
  get	'/service/:short_link(.:format)', :to=>'services#show', :as=>:service


  #resources :teams
  get '/team', :to => "teams#index", :as => :teams
  get	'/team/:short_link(.:format)', :to=>'teams#show', :as=>:team

  #resources :works,:only=>[:index, :show], except: :destroy
  get '/work', :to => "works#index", :as => :works
  get	'/work/:short_link(.:format)', :to=>'works#show', :as=>:work

  #resources :contacts
  get '/contact', :to => "contacts#new", :as => :new_contact
  post '/contact', :to => "contacts#create", :as => :create_contact
  resources :contacts, :only => [:new, :create], :path => 'contacts'

  #resources :project_planners
  get '/project-planner', :to => "project_planners#new", :as => :new_project_planner
  post '/project-planner', :to => "project_planners#create", :as => :create_project_planner
  resources :project_planners, :only => [:new, :create], :path => 'project_planners'

  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/home_slider.rb
class HomeSlider < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
end

app/models/page_meta_info.rb
class PageMetaInfo < ActiveRecord::Base
end

app/models/page_setting.rb
class PageSetting < ActiveRecord::Base
end

app/models/project_planner.rb
class ProjectPlanner < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :homepage_icon, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :homepage_icon_hover, :styles => { :medium => "300x300>", :thumb=> "100x100>" }

  validates_attachment :homepage_icon, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  validates_attachment :homepage_icon_hover, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  has_many :service_sliders

  def to_param
    short_link
  end
end

app/models/service_slider.rb
class ServiceSlider < ActiveRecord::Base
  has_attached_file :navigation_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :navigation_image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :service
end

app/models/site_config.rb
class SiteConfig < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  has_many :team_sliders

  def to_param
    short_link
  end

end

app/models/team_slider.rb
class TeamSlider < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  has_many :work_sliders

  def to_param
    short_link
  end
end

app/models/work_slider.rb
class WorkSlider < ActiveRecord::Base
  has_attached_file :navigation_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :navigation_image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :work
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { render :new }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :full_name, :company, :subject, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @services = Service.all
    @home_sliders = HomeSlider.order('home_sliders.order').all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_sliders_helper.rb
module HomeSlidersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/contacts/_form.html.erb
<section id="contact-top">
  <div class="wrapper">
    <h1>Contact Us</h1>

    <div class="phone-wrapper">
      <a class="number-box" href="#"><i class="fa fa-phone"></i>(310) 707 - 3289</a><span>Give us a call!</span>
    </div>

    <div class="button-wrapper">
      <!--<a href="project-planner.html">Try Out Project Planner</a>-->
      <%= link_to 'Try Out Project Planner',new_project_planner_path %>
    </div>
  </div>
</section>

<section id="contact-area">
  <div class="wrapper">
    <div class="contact-box">
      <h6>Lets Get In Touch!</h6>

      <%= form_for @contact,url: {action: "new"} do |f| %>
          <% if @contact.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

                <ul>
                  <% @contact.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
        <div class="field-columns">
          <div class="left-column">
            <%= f.text_field :full_name,:class=>'field-textbox', :placeholder=>'First & Last Name' %>
            <%= f.text_field :company,:class=>'field-textbox', :placeholder=>'Company (optional)' %>
            <%= f.text_field :email,:class=>'field-textbox', :placeholder=>'Email Address' %>
            <%= f.text_field :subject,:class=>'field-textbox', :placeholder=>'Subject' %>
          </div>

          <div class="right-column">
            <%= f.text_area :message, :class=>'field-textarea',:placeholder =>'Message...' %>
          </div>

          <br class="clearBoth field-clear" />
        </div>

        <div class="button-wrapper">
          <%= f.submit 'Send Mail',:class=>'mail-button' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<section id="contact-map-area">
  <div class="wrapper">
    <div class="map-holder">
      <!--<img src="/img/contact-map.png" /-->
      <%= image_tag 'contact-map.png'%>
    </div>
  </div>
</section>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Full name</th>
      <th>Company</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= contact.full_name %></td>
        <td><%= contact.company %></td>
        <td><%= contact.subject %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @contact.full_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>