config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :site_configs

  resources :page_meta_infos

  resources :home_sliders

  resources :work_sliders

  resources :team_sliders

  resources :service_sliders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  #resources :services
  get '/service', :to => "services#index", :as => :services
  get	'/service/:short_link(.:format)', :to=>'services#show', :as=>:service


  #resources :teams
  get '/team', :to => "teams#index", :as => :teams
  get	'/team/:short_link(.:format)', :to=>'teams#show', :as=>:team

  #resources :works,:only=>[:index, :show], except: :destroy
  get '/work', :to => "works#index", :as => :works
  get	'/work/:short_link(.:format)', :to=>'works#show', :as=>:work

  #resources :contacts
  get '/contact', :to => "contacts#new", :as => :new_contact
  post '/contact', :to => "contacts#create", :as => :create_contact
  resources :contacts, :only => [:new, :create], :path => 'contacts'

  #resources :project_planners
  get '/project-planner', :to => "project_planners#new", :as => :new_project_planner
  post '/project-planner', :to => "project_planners#create", :as => :create_project_planner
  resources :project_planners, :only => [:new, :create], :path => 'project_planners'

  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/home_slider.rb
class HomeSlider < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
end

app/models/page_meta_info.rb
class PageMetaInfo < ActiveRecord::Base
end

app/models/page_setting.rb
class PageSetting < ActiveRecord::Base
end

app/models/project_planner.rb
class ProjectPlanner < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :homepage_icon, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :homepage_icon_hover, :styles => { :medium => "300x300>", :thumb=> "100x100>" }

  validates_attachment :homepage_icon, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  validates_attachment :homepage_icon_hover, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  has_many :service_sliders

  def to_param
    short_link
  end
end

app/models/service_slider.rb
class ServiceSlider < ActiveRecord::Base
  has_attached_file :navigation_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :navigation_image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :service
end

app/models/site_config.rb
class SiteConfig < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  has_many :team_sliders

  def to_param
    short_link
  end

end

app/models/team_slider.rb
class TeamSlider < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }
  has_many :work_sliders

  def to_param
    short_link
  end
end

app/models/work_slider.rb
class WorkSlider < ActiveRecord::Base
  has_attached_file :navigation_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :navigation_image, content_type: { content_type: ["image/jpg", "image/jpeg",   "image/png"] }

  belongs_to :work
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @services = Service.all
    @home_sliders = HomeSlider.order('home_sliders.order').all
  end
end

app/controllers/project_planners_controller.rb
class ProjectPlannersController < ApplicationController
  before_action :set_project_planner, only: [:show, :edit, :update, :destroy]

  # GET /project_planners
  # GET /project_planners.json
  def index
    @project_planners = ProjectPlanner.all
  end

  # GET /project_planners/1
  # GET /project_planners/1.json
  def show
  end

  # GET /project_planners/new
  def new
    @project_planner = ProjectPlanner.new
  end

  # GET /project_planners/1/edit
  def edit
  end

  # POST /project_planners
  # POST /project_planners.json
  def create
    @project_planner = ProjectPlanner.new(project_planner_params)

    respond_to do |format|
      if @project_planner.save
        #format.html { redirect_to @project_planner, notice: 'Project planner was successfully created.' }
        format.html { render :new }
        format.json { render :show, status: :created, location: @project_planner }
      else
        format.html { render :new }
        format.json { render json: @project_planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_planners/1
  # PATCH/PUT /project_planners/1.json
  def update
    respond_to do |format|
      if @project_planner.update(project_planner_params)
        format.html { redirect_to @project_planner, notice: 'Project planner was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_planner }
      else
        format.html { render :edit }
        format.json { render json: @project_planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_planners/1
  # DELETE /project_planners/1.json
  def destroy
    @project_planner.destroy
    respond_to do |format|
      format.html { redirect_to project_planners_url, notice: 'Project planner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_planner
      @project_planner = ProjectPlanner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_planner_params
      params.require(:project_planner).permit(:full_name, :company, :phone_number, :email_address, :hear_about_us, :project_url, :launch_date, :budget, :site_concept, :main_objective, :schedule_considerations)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_planners_helper.rb
module ProjectPlannersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/project_planners/_form.html.erb
<section id="project-planner-top">
  <div class="wrapper">
    <h1>Project Planner</h1>

    <div class="phone-wrapper">
      <a class="number-box" href="#"><i class="fa fa-phone"></i>(310) 707 - 3289</a><span>Give us a call!</span>
    </div>
  </div>
</section>
<%= form_for @project_planner, url:{action: "new"} do |f| %>
  <% if @project_planner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_planner.errors.count, "error") %> prohibited this project_planner from being saved:</h2>

      <ul>
      <% @project_planner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <section id="planner-first-section" class="planner-section">
      <div class="wrapper">
        <h6>1. Contact Info</h6>
        <div class="field-holder first-last-name-field-holder">
          <label for="first-last-name-field">First & Last Name:</label>
          <!--<input id="first-last-name-field" type="text" name="first_and_last_name" class="field-textbox" value=""/>-->
          <%= f.text_field :full_name, :class=>'field-textbox' %>
        </div>

        <div class="field-holder company-name-field-holder">
          <label for="company-name-field">Company or Organization Name:</label>
          <!--<input id="company-name-field" type="text" name="company_name" class="field-textbox" value=""/>-->
          <%= f.text_field :company, :class=>'field-textbox' %>
        </div>

        <div class="field-holder phone-number-field-holder">
          <label for="phone-number-field">Phone Number:</label>
          <!--<input id="phone-number-field" type="text" name="phone_number" class="field-textbox" value=""/>-->
          <%= f.text_field :phone_number, :class=>'field-textbox' %>
        </div>

        <div class="field-holder email-address-field-holder">
          <label for="email-address-field">Email Address:</label>
          <!--<input id="email-address-field" type="email" name="email_address" class="field-textbox" value=""/>-->
          <%= f.text_field :email_address, :class=>'field-textbox' %>
        </div>

        <div class="field-holder referral-field-holder">
          <label for="referral-field">How did you hear about us?</label>
          <!--<input id="referral-field" type="text" name="referral" class="field-textbox" value=""/>-->
          <%= f.text_field :hear_about_us, :class=>'field-textbox' %>
        </div>
      </div>
    </section>

    <section id="planner-second-section" class="planner-section">
      <div class="wrapper">
        <h6>2. General Project Info</h6>
        <div class="field-holder project-url-field-holder">
          <label for="project-url-field">What is your current (or intended) URL?</label>
          <!--<input id="project-url-field" type="text" name="project_url" class="field-textbox" value=""/>-->
          <%= f.text_field :project_url, :class=>'field-textbox' %>
        </div>

        <div class="field-holder launch-date-field-holder">
          <label for="launch-date-field">What is your desired Launch Date?</label>
          <!--<input id="launch-date-field" type="text" name="launch_date" class="field-textbox" value=""/>-->
          <%= f.text_field :launch_date,:class=>'field-textbox' %>
        </div>

        <div class="field-holder budget-field-holder">
          <label class="budget-label">Do you have a budget already established for this project? If so, please indicate your budget below:</label>
          <input id="budget-radio-under-5k" type="radio" class="field-radio" name="project_planner[budget]" value="5000" />
          <label for="budget-radio-under-5k" class="radio-label">Under $5,000</label>

          <input id="budget-radio-5k-10k" type="radio" class="field-radio" name="project_planner[budget]" value="10000" />
          <label for="budget-radio-5k-10k" class="radio-label">$5,000 - $10g,000</label>

          <input id="budget-radio-10k-30k" type="radio" class="field-radio" name="project_planner[budget]" value="30000" />
          <label for="budget-radio-10k-30k" class="radio-label">$10,000 - $30,000</label>

          <input id="budget-radio-30k-50k-plus" type="radio" class="field-radio" name="project_planner[budget]" value="50000" />
          <label for="budget-radio-30k-50k-plus" class="radio-label">$30,000 - $50,000+</label>

          <input id="budget-radio-unknown" type="radio" class="field-radio" name="project_planner[budget]" value="Unknown" />
          <label for="budget-radio-unknown" class="radio-label">Unknown</label>
        </div>
      </div>
    </section>

    <section id="planner-third-section" class="planner-section">
      <div class="wrapper">
        <h6>3. Project Goals</h6>

        <div class="field-holder site-concept-field-holder">
          <label for="site-concept-field">Briefly describe the site's concept and what service it seeks to provide.</label>
          <!--<textarea id="site-concept-field" name="site_concept" class="field-textarea"></textarea>-->
          <%= f.text_area :site_concept, :class=>'field-textarea' %>
        </div>

        <div class="field-holder main-objective-field-holder">
          <label for="main-objective-field">What is your main objective or reason for this project?</label>
          <!--<textarea id="main-objective-field" name="main_objective" class="field-textarea"></textarea>-->
          <%= f.text_area :main_objective, :class=>'field-textarea' %>
        </div>

        <div class="field-holder schedule-considerations-field-holder">
          <label for="schedule-considerations-field">Are there any other considerations that could impact the project schedule?</label>
          <!--<textarea id="schedule-considerations-field" name="schedule_considerations" class="field-textarea"></textarea>-->
          <%= f.text_area :schedule_considerations, :class=>'field-textarea' %>
        </div>
      </div>
    </section>

    <section id="planner-fourth-section" class="planner-section">
      <div class="wrapper">
       <!-- <div class="legal-holder">
          <input id="legal-disclaimer-field" type="checkbox" class="field-checkbox" name="legal_disclaimer" value="1" />
          <label for="legal-disclaimer-field" class="legal-label">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisl velit, suscipit a orci et.</label>
        </div>-->

        <div class="button-holder">
          <!--<a href="#" type="submit">Submit Form</a>-->
          <%= f.submit 'Submit Form', :class=>'submit-button' %>
        </div>

        <br class="clearBoth bottom-clear" />
      </div>
    </section>
<% end %>

app/views/project_planners/edit.html.erb
<h1>Editing project_planner</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_planner %> |
<%= link_to 'Back', project_planners_path %>

app/views/project_planners/index.html.erb
<h1>Listing project_planners</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Company</th>
      <th>Phone number</th>
      <th>Email address</th>
      <th>Hear about us</th>
      <th>Project url</th>
      <th>Launch date</th>
      <th>Budget</th>
      <th>Site concept</th>
      <th>Main objective</th>
      <th>Schedule considerations</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_planners.each do |project_planner| %>
      <tr>
        <td><%= project_planner.full_name %></td>
        <td><%= project_planner.company %></td>
        <td><%= project_planner.phone_number %></td>
        <td><%= project_planner.email_address %></td>
        <td><%= project_planner.hear_about_us %></td>
        <td><%= project_planner.project_url %></td>
        <td><%= project_planner.launch_date %></td>
        <td><%= project_planner.budget %></td>
        <td><%= project_planner.site_concept %></td>
        <td><%= project_planner.main_objective %></td>
        <td><%= project_planner.schedule_considerations %></td>
        <td><%= link_to 'Show', project_planner %></td>
        <td><%= link_to 'Edit', edit_project_planner_path(project_planner) %></td>
        <td><%= link_to 'Destroy', project_planner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project planner', new_project_planner_path %>

app/views/project_planners/new.html.erb
<%= render 'form' %>

app/views/project_planners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @project_planner.full_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @project_planner.company %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @project_planner.phone_number %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @project_planner.email_address %>
</p>

<p>
  <strong>Hear about us:</strong>
  <%= @project_planner.hear_about_us %>
</p>

<p>
  <strong>Project url:</strong>
  <%= @project_planner.project_url %>
</p>

<p>
  <strong>Launch date:</strong>
  <%= @project_planner.launch_date %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @project_planner.budget %>
</p>

<p>
  <strong>Site concept:</strong>
  <%= @project_planner.site_concept %>
</p>

<p>
  <strong>Main objective:</strong>
  <%= @project_planner.main_objective %>
</p>

<p>
  <strong>Schedule considerations:</strong>
  <%= @project_planner.schedule_considerations %>
</p>

<%= link_to 'Edit', edit_project_planner_path(@project_planner) %> |
<%= link_to 'Back', project_planners_path %>